"""
Django settings for meeting_agent project.

Generated by 'django-admin startproject' using Django 5.2.3.
<<<<<<< HEAD

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p*=zh&_7eid!!&!tm+r7qgj+!gr^*w)9s4tw$fkdprrrfmq-24'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
=======
"""
import os
from dotenv import load_dotenv

load_dotenv()  

from pathlib import Path
from decouple import config
GROQ_API_KEY = config('GROQ_API_KEY', default='dummy_value')  # Use decouple to manage environment variables


# BASE_DIR setup
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = 'django-insecure-p*=zh&_7eid!!&!tm+r7qgj+!gr^*w)9s4tw$fkdprrrfmq-24'
DEBUG = True
ALLOWED_HOSTS = []

# APPLICATION DEFINITION
INSTALLED_APPS = [
    # — Your apps —
    'login_signup_app',
    'create_meeting_app',
    'landing_page',

    # — Django built-ins —
>>>>>>> 3c1b82c32efc8d5ab0d855a36c6c86fc3a730fba
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'landing_page',
    'create_meeting_app',
]

=======
    'django_apscheduler',

    # — Allauth & Social Auth —
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]


SITE_ID = 1

>>>>>>> 3c1b82c32efc8d5ab0d855a36c6c86fc3a730fba
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
<<<<<<< HEAD
=======
    'allauth.account.middleware.AccountMiddleware',  
>>>>>>> 3c1b82c32efc8d5ab0d855a36c6c86fc3a730fba
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<< HEAD
ROOT_URLCONF = 'meeting_agent.urls'

=======

ROOT_URLCONF = 'meeting_agent.urls'

# TEMPLATES: include a top‑level templates/ folder
>>>>>>> 3c1b82c32efc8d5ab0d855a36c6c86fc3a730fba
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
<<<<<<< HEAD
                'django.template.context_processors.request',
=======
                'django.template.context_processors.request',  # required by allauth
>>>>>>> 3c1b82c32efc8d5ab0d855a36c6c86fc3a730fba
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meeting_agent.wsgi.application'

<<<<<<< HEAD

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

=======
# DATABASE (SQLite for dev)
>>>>>>> 3c1b82c32efc8d5ab0d855a36c6c86fc3a730fba
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

<<<<<<< HEAD

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'landing_page/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
=======
# AUTHENTICATION BACKENDS
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',             # default
    'allauth.account.auth_backends.AuthenticationBackend',   # allauth
]

# django‑allauth CONFIGURATION
ACCOUNT_EMAIL_REQUIRED        = True
ACCOUNT_USERNAME_REQUIRED     = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION    = 'optional'

LOGIN_REDIRECT_URL  = '/dashboard/'   # after login/signup
LOGOUT_REDIRECT_URL = '/login/'       # after logout

# SOCIALACCOUNT PROVIDERS (Google OAuth keys go here)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        }
    }
}

# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ... the top half remains the same ...

# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'Asia/Dhaka'
USE_I18N      = True
USE_TZ        = True

# STATIC FILES
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'login_signup_app' / 'static',
    BASE_DIR / 'create_meeting_app' / 'static',
    BASE_DIR / 'landing_page' / 'static',
]

# When you run `collectstatic`, everything will go here:
STATIC_ROOT = BASE_DIR / 'staticfiles'

# DEFAULT PRIMARY KEY FIELD TYPE
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL BACKEND (console for dev)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
>>>>>>> 3c1b82c32efc8d5ab0d855a36c6c86fc3a730fba
